backend:
  name: github
  repo: Twinpixel-nl/SocialmediaManager-Website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publicatiedatum", name: "date", widget: "datetime" }
      - { label: "Inhoud", name: "body", widget: "markdown" }
