backend:
  name: git-gateway
  repo: Twinpixel-nl/SocialmediaManager-Website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://socialmediamanager.nl/

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publicatiedatum", name: "date", widget: "datetime" }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
          hint: "Gebruik een liggende afbeelding (minimaal 1200x675px voor beste resultaat)",
        }
      - {
          label: "ondertiteling",
          name: "excerpt",
          widget: "string",
          required: false,
        }
      - { label: "Inhoud", name: "body", widget: "markdown" }
